### ISSUE TITLE
Importing 2 or more wp galleries

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-importer#5]
When importing 2 or more galleries from the same page, the later galleries import it's images and the images from the previous galleries.

**Comment by andrei-l-cristea** [comment]
Tested this by importing two WP Core Galleries from the same page and each one had the proper images contained. A little suggestion, the name of both galleries was the same, think we should include the id or something so that customers can tell the galleries apart:
![image](https://user-images.githubusercontent.com/53428716/73458981-c9467680-437e-11ea-8c21-e372d647aa80.png)

**Comment by razvanaldea89** [comment]
Can't really include id, it is same id ( page id )

**Comment by andrei-l-cristea** [comment]
Then use an automatically incremented number? Like Gallery from sample page 1, Gallery from sample page 2....?

**Comment by giucu91** [comment]
@razvanaldea89 we should add #1 #2 if there are more than 1 in the same page.

**Comment by andyluak** [comment]
The galleries import only the right images . Working

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/75868621-fc15db80-5e10-11ea-8f28-2817f3e9990b.png)

here should be :
Gallery #2 from WP Core Galleries
Gallery #1 from WP Core Galleries
